spring:
  application:
    name: demo

  datasource:
    driver-class-name: org.postgresql.Driver
    username: user
    password: pass
    url: jdbc:postgresql://localhost:5432/project_db

  thymeleaf:
    cache: false
    encoding: utf-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

  mvc:
    hiddenmethod:
      filter:
        enabled: true
